#============================
# サーバー／クライアント共通
#============================

# 定数
CONSTANTS:
  # 権限
  SCOPE:
    PUBLIC: { VALUE: &SCP_PUB 1, NAME: "一般者" }
    READER: { VALUE: &SCP_RED 2, NAME: "閲覧者" }
    MODIFIER: { VALUE: &SCP_MOD 5, NAME: "更新者" }
    ADMINISTRATOR: { VALUE: &SCP_ADM 9, NAME: "管理者" }


# ページ情報
pageItems:
  - icon: "fa-home"
    title: "トップ"
    path: "/"
    scopelevel: *SCP_PUB
  - icon: "fa-place-of-worship"
    title: "エリア・地域 メンテナンス"
    path: "/area"
    scopelevel: *SCP_RED
  - icon: "fa-train"
    title: "沿線・駅 メンテナンス"
    path: "/railway_line"
    scopelevel: *SCP_RED
  - icon: "fa-cloud-upload-alt"
    title: "インポート"
    path: "/import"
    scopelevel: *SCP_MOD
  - icon: "fa-address-card"
    title: "ユーザー管理"
    path: "/user"
    scopelevel: *SCP_ADM


#===========================================================
# 以下はサーバー設定のみ使用（nuxtのenvには公開してはいけない）
#===========================================================

# JSON Web Token
jwt:
  secret: "7$|i93x%6z)P"
  expiresIn: "1h"
  ignorePath: ["/api/auth/login"]

# 暗号化
crypto:
  key: "K2UL3Q6FM6KL"

# DB(MySQL)
db:
  username: "adminuser"
  password: "mypass"
  database: "simple_mst"
  host: "db"
  port: 3306
  connectionLimit: 10
  dialect: "mysql"
  operatorsAliases: "false"

# インポート設定
import:
  table:
    address:
      name: "m_address"
      ignoreLines: 1
      encoding: "Shift_JIS"
    company:
      name: "m_company"
      ignoreLines: 1
    line:
      name: "m_line"
      ignoreLines: 1
    station:
      name: "m_station"
      ignoreLines: 1
    stationjoin:
      name: "m_station_join"
      ignoreLines: 1
